// <auto-generated />
namespace Capstone_Wishlist_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedchildtoDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedchildtoDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281912401_added child to DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
