// <auto-generated />
namespace Capstone_Wishlist_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class change_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201510100146443_change_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
